# Generated by Django 4.1.7 on 2023-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
