# Generated by Django 4.1.7 on 2023-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_groupchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation_section',
            name='affiliation_position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
