# Generated by Django 4.1.7 on 2023-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haiku',
        ),
        migrations.AlterField(
            model_name='schoolgym',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='studio45_code.tag'),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='studio45_code.tag'),
        ),
    ]
