# Generated by Django 4.1.7 on 2023-06-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0002_delete_haiku_alter_schoolgym_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='website',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='schoolgym',
            name='website',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
