# Generated by Django 4.1.10 on 2023-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0005_schoolgym_state_alter_schoolgym_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgym',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
