# Generated by Django 4.1.10 on 2023-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0006_alter_schoolgym_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgym',
            name='Entry_Associate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgym',
            name='Facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgym',
            name='Google_My_Business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgym',
            name='Instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgym',
            name='School_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgym',
            name='Twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
