# Generated by Django 4.1.10 on 2023-07-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0008_rename_image_schoolgym_image_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolgym',
            old_name='image_urls',
            new_name='image',
        ),
    ]
