# Generated by Django 4.1.10 on 2023-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0009_rename_image_urls_schoolgym_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarinformation',
            name='details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='does_this_event_accept_foreign_participants',
            field=models.CharField(blank=True, default=False, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='online_only',
            field=models.CharField(blank=True, default=False, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
