# Generated by Django 4.1.10 on 2023-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0010_alter_seminarinformation_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarinformation',
            name='cost_of_seminar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seminarinformation',
            name='social_media_links',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
