# Generated by Django 4.1.10 on 2023-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0012_alter_seminarinformation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgym',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminarinformation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
