# Generated by Django 4.1.10 on 2023-07-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio45_code', '0014_alter_events_address_alter_events_contact_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolgym',
            old_name='owner_email',
            new_name='SchoolGym_email',
        ),
    ]
